- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS from PLAY level"
    DURATION: "120Hrs"
    TRAINER: "Rajesh"  
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false # not confidential (it will show what u typed in prompt)
  - name: DURATION
    prompt: Please enter the duration name
  - name: TRAINER
    prompt: Please enter the trainer name  
  tasks:
  - name: print the information
    vars:
      COURSE: "DevOps with AWS from TASK level"
      DURATION: "120Hrs"
      TRAINER: "Rajesh"  
    ansible.builtin.debug:
      msg: "Hi, i am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"   

