- name: un install packages from installed ones
  hosts: web
  become: yes
  tasks:
  - name: un and in install packages
    ansible.builtin.packages:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'httpd', state: 'present' }
