- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      # msg: "Hello {{ course }}"
      msg: "Hello {{ course | default('Ansible') }}"

  - name: Convert to Uppercase
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }} "
      #msg: " {{ greeting | lower }} "
  - name: convert to lowercase
    vars:
      greeting: "Hello Rajesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }} "  
  - name: get the unique values
    vars:
      numbers: [1,2,3,5,3,2,7]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max values
    vars:
      numbers: [1,2,3,5,3,2,7]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "Siva"
    ansible.builtin.debug:
      msg: " {{ course | dict2items }} "

  - name: convert list to map
    vars:
      course:
      - { "key": "name","value": "DevOps with AWS"}
      - { "key": "duration","value": 120 }
      - { "key": "trainer","value": "siva" }
    ansible.builtin.debug:
      msg: " {{ course | items2dict }} "
          